/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app/workouts/index'
import { Route as AppLogWorkoutIndexRouteImport } from './routes/app/log-workout/index'
import { Route as AppWorkoutsNotFoundIndexRouteImport } from './routes/app/workouts/not-found/index'
import { Route as AppWorkoutsInvalidIndexRouteImport } from './routes/app/workouts/invalid/index'
import { Route as AppWorkoutsIdIndexRouteImport } from './routes/app/workouts/$id/index'
import { Route as AppAdminWorkoutTemplatesIndexRouteImport } from './routes/app/admin/workout-templates/index'
import { Route as AppAdminSettingsIndexRouteImport } from './routes/app/admin/settings/index'
import { Route as AppAdminExercisesIndexRouteImport } from './routes/app/admin/exercises/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogWorkoutIndexRoute = AppLogWorkoutIndexRouteImport.update({
  id: '/log-workout/',
  path: '/log-workout/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsNotFoundIndexRoute =
  AppWorkoutsNotFoundIndexRouteImport.update({
    id: '/workouts/not-found/',
    path: '/workouts/not-found/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkoutsInvalidIndexRoute = AppWorkoutsInvalidIndexRouteImport.update({
  id: '/workouts/invalid/',
  path: '/workouts/invalid/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsIdIndexRoute = AppWorkoutsIdIndexRouteImport.update({
  id: '/workouts/$id/',
  path: '/workouts/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminWorkoutTemplatesIndexRoute =
  AppAdminWorkoutTemplatesIndexRouteImport.update({
    id: '/workout-templates/',
    path: '/workout-templates/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminSettingsIndexRoute = AppAdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppAdminExercisesIndexRoute = AppAdminExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout/': typeof AppLogWorkoutIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises/': typeof AppAdminExercisesIndexRoute
  '/app/admin/settings/': typeof AppAdminSettingsIndexRoute
  '/app/admin/workout-templates/': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/$id/': typeof AppWorkoutsIdIndexRoute
  '/app/workouts/invalid/': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found/': typeof AppWorkoutsNotFoundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout': typeof AppLogWorkoutIndexRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises': typeof AppAdminExercisesIndexRoute
  '/app/admin/settings': typeof AppAdminSettingsIndexRoute
  '/app/admin/workout-templates': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/$id': typeof AppWorkoutsIdIndexRoute
  '/app/workouts/invalid': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found': typeof AppWorkoutsNotFoundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/log-workout/': typeof AppLogWorkoutIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises/': typeof AppAdminExercisesIndexRoute
  '/app/admin/settings/': typeof AppAdminSettingsIndexRoute
  '/app/admin/workout-templates/': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/$id/': typeof AppWorkoutsIdIndexRoute
  '/app/workouts/invalid/': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found/': typeof AppWorkoutsNotFoundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout/'
    | '/app/workouts/'
    | '/app/admin/exercises/'
    | '/app/admin/settings/'
    | '/app/admin/workout-templates/'
    | '/app/workouts/$id/'
    | '/app/workouts/invalid/'
    | '/app/workouts/not-found/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout'
    | '/app/workouts'
    | '/app/admin/exercises'
    | '/app/admin/settings'
    | '/app/admin/workout-templates'
    | '/app/workouts/$id'
    | '/app/workouts/invalid'
    | '/app/workouts/not-found'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout/'
    | '/app/workouts/'
    | '/app/admin/exercises/'
    | '/app/admin/settings/'
    | '/app/admin/workout-templates/'
    | '/app/workouts/$id/'
    | '/app/workouts/invalid/'
    | '/app/workouts/not-found/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/log-workout/': {
      id: '/app/log-workout/'
      path: '/log-workout'
      fullPath: '/app/log-workout/'
      preLoaderRoute: typeof AppLogWorkoutIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/not-found/': {
      id: '/app/workouts/not-found/'
      path: '/workouts/not-found'
      fullPath: '/app/workouts/not-found/'
      preLoaderRoute: typeof AppWorkoutsNotFoundIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/invalid/': {
      id: '/app/workouts/invalid/'
      path: '/workouts/invalid'
      fullPath: '/app/workouts/invalid/'
      preLoaderRoute: typeof AppWorkoutsInvalidIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/$id/': {
      id: '/app/workouts/$id/'
      path: '/workouts/$id'
      fullPath: '/app/workouts/$id/'
      preLoaderRoute: typeof AppWorkoutsIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/workout-templates/': {
      id: '/app/admin/workout-templates/'
      path: '/workout-templates'
      fullPath: '/app/admin/workout-templates/'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/settings/': {
      id: '/app/admin/settings/'
      path: '/settings'
      fullPath: '/app/admin/settings/'
      preLoaderRoute: typeof AppAdminSettingsIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/exercises/': {
      id: '/app/admin/exercises/'
      path: '/exercises'
      fullPath: '/app/admin/exercises/'
      preLoaderRoute: typeof AppAdminExercisesIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminExercisesIndexRoute: typeof AppAdminExercisesIndexRoute
  AppAdminSettingsIndexRoute: typeof AppAdminSettingsIndexRoute
  AppAdminWorkoutTemplatesIndexRoute: typeof AppAdminWorkoutTemplatesIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminExercisesIndexRoute: AppAdminExercisesIndexRoute,
  AppAdminSettingsIndexRoute: AppAdminSettingsIndexRoute,
  AppAdminWorkoutTemplatesIndexRoute: AppAdminWorkoutTemplatesIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppLogWorkoutIndexRoute: typeof AppLogWorkoutIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
  AppWorkoutsIdIndexRoute: typeof AppWorkoutsIdIndexRoute
  AppWorkoutsInvalidIndexRoute: typeof AppWorkoutsInvalidIndexRoute
  AppWorkoutsNotFoundIndexRoute: typeof AppWorkoutsNotFoundIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppLogWorkoutIndexRoute: AppLogWorkoutIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
  AppWorkoutsIdIndexRoute: AppWorkoutsIdIndexRoute,
  AppWorkoutsInvalidIndexRoute: AppWorkoutsInvalidIndexRoute,
  AppWorkoutsNotFoundIndexRoute: AppWorkoutsNotFoundIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
