/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAdminRouteRouteImport } from './routes/app/admin/route'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app/workouts/index'
import { Route as AppLogWorkoutIndexRouteImport } from './routes/app/log-workout/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppWorkoutsNotFoundIndexRouteImport } from './routes/app/workouts/not-found/index'
import { Route as AppWorkoutsInvalidIndexRouteImport } from './routes/app/workouts/invalid/index'
import { Route as AppAdminWorkoutTemplatesIndexRouteImport } from './routes/app/admin/workout-templates/index'
import { Route as AppAdminExercisesIndexRouteImport } from './routes/app/admin/exercises/index'
import { Route as AppWorkoutsEditIdIndexRouteImport } from './routes/app/workouts/edit/$id/index'
import { Route as AppAdminWorkoutTemplatesNotFoundIndexRouteImport } from './routes/app/admin/workout-templates/not-found/index'
import { Route as AppAdminWorkoutTemplatesCreateIndexRouteImport } from './routes/app/admin/workout-templates/create/index'
import { Route as AppAdminWorkoutTemplatesEditIdIndexRouteImport } from './routes/app/admin/workout-templates/edit/$id/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRouteRoute = AppAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogWorkoutIndexRoute = AppLogWorkoutIndexRouteImport.update({
  id: '/log-workout/',
  path: '/log-workout/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppWorkoutsNotFoundIndexRoute =
  AppWorkoutsNotFoundIndexRouteImport.update({
    id: '/workouts/not-found/',
    path: '/workouts/not-found/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppWorkoutsInvalidIndexRoute = AppWorkoutsInvalidIndexRouteImport.update({
  id: '/workouts/invalid/',
  path: '/workouts/invalid/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminWorkoutTemplatesIndexRoute =
  AppAdminWorkoutTemplatesIndexRouteImport.update({
    id: '/workout-templates/',
    path: '/workout-templates/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminExercisesIndexRoute = AppAdminExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => AppAdminRouteRoute,
} as any)
const AppWorkoutsEditIdIndexRoute = AppWorkoutsEditIdIndexRouteImport.update({
  id: '/workouts/edit/$id/',
  path: '/workouts/edit/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminWorkoutTemplatesNotFoundIndexRoute =
  AppAdminWorkoutTemplatesNotFoundIndexRouteImport.update({
    id: '/workout-templates/not-found/',
    path: '/workout-templates/not-found/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminWorkoutTemplatesCreateIndexRoute =
  AppAdminWorkoutTemplatesCreateIndexRouteImport.update({
    id: '/workout-templates/create/',
    path: '/workout-templates/create/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)
const AppAdminWorkoutTemplatesEditIdIndexRoute =
  AppAdminWorkoutTemplatesEditIdIndexRouteImport.update({
    id: '/workout-templates/edit/$id/',
    path: '/workout-templates/edit/$id/',
    getParentRoute: () => AppAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/log-workout/': typeof AppLogWorkoutIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises/': typeof AppAdminExercisesIndexRoute
  '/app/admin/workout-templates/': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/invalid/': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found/': typeof AppWorkoutsNotFoundIndexRoute
  '/app/admin/workout-templates/create/': typeof AppAdminWorkoutTemplatesCreateIndexRoute
  '/app/admin/workout-templates/not-found/': typeof AppAdminWorkoutTemplatesNotFoundIndexRoute
  '/app/workouts/edit/$id/': typeof AppWorkoutsEditIdIndexRoute
  '/app/admin/workout-templates/edit/$id/': typeof AppAdminWorkoutTemplatesEditIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminIndexRoute
  '/app/log-workout': typeof AppLogWorkoutIndexRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises': typeof AppAdminExercisesIndexRoute
  '/app/admin/workout-templates': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/invalid': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found': typeof AppWorkoutsNotFoundIndexRoute
  '/app/admin/workout-templates/create': typeof AppAdminWorkoutTemplatesCreateIndexRoute
  '/app/admin/workout-templates/not-found': typeof AppAdminWorkoutTemplatesNotFoundIndexRoute
  '/app/workouts/edit/$id': typeof AppWorkoutsEditIdIndexRoute
  '/app/admin/workout-templates/edit/$id': typeof AppAdminWorkoutTemplatesEditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/admin': typeof AppAdminRouteRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/log-workout/': typeof AppLogWorkoutIndexRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
  '/app/admin/exercises/': typeof AppAdminExercisesIndexRoute
  '/app/admin/workout-templates/': typeof AppAdminWorkoutTemplatesIndexRoute
  '/app/workouts/invalid/': typeof AppWorkoutsInvalidIndexRoute
  '/app/workouts/not-found/': typeof AppWorkoutsNotFoundIndexRoute
  '/app/admin/workout-templates/create/': typeof AppAdminWorkoutTemplatesCreateIndexRoute
  '/app/admin/workout-templates/not-found/': typeof AppAdminWorkoutTemplatesNotFoundIndexRoute
  '/app/workouts/edit/$id/': typeof AppWorkoutsEditIdIndexRoute
  '/app/admin/workout-templates/edit/$id/': typeof AppAdminWorkoutTemplatesEditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/admin/'
    | '/app/log-workout/'
    | '/app/workouts/'
    | '/app/admin/exercises/'
    | '/app/admin/workout-templates/'
    | '/app/workouts/invalid/'
    | '/app/workouts/not-found/'
    | '/app/admin/workout-templates/create/'
    | '/app/admin/workout-templates/not-found/'
    | '/app/workouts/edit/$id/'
    | '/app/admin/workout-templates/edit/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/log-workout'
    | '/app/workouts'
    | '/app/admin/exercises'
    | '/app/admin/workout-templates'
    | '/app/workouts/invalid'
    | '/app/workouts/not-found'
    | '/app/admin/workout-templates/create'
    | '/app/admin/workout-templates/not-found'
    | '/app/workouts/edit/$id'
    | '/app/admin/workout-templates/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/admin/'
    | '/app/log-workout/'
    | '/app/workouts/'
    | '/app/admin/exercises/'
    | '/app/admin/workout-templates/'
    | '/app/workouts/invalid/'
    | '/app/workouts/not-found/'
    | '/app/admin/workout-templates/create/'
    | '/app/admin/workout-templates/not-found/'
    | '/app/workouts/edit/$id/'
    | '/app/admin/workout-templates/edit/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/log-workout/': {
      id: '/app/log-workout/'
      path: '/log-workout'
      fullPath: '/app/log-workout/'
      preLoaderRoute: typeof AppLogWorkoutIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/workouts/not-found/': {
      id: '/app/workouts/not-found/'
      path: '/workouts/not-found'
      fullPath: '/app/workouts/not-found/'
      preLoaderRoute: typeof AppWorkoutsNotFoundIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workouts/invalid/': {
      id: '/app/workouts/invalid/'
      path: '/workouts/invalid'
      fullPath: '/app/workouts/invalid/'
      preLoaderRoute: typeof AppWorkoutsInvalidIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/workout-templates/': {
      id: '/app/admin/workout-templates/'
      path: '/workout-templates'
      fullPath: '/app/admin/workout-templates/'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/exercises/': {
      id: '/app/admin/exercises/'
      path: '/exercises'
      fullPath: '/app/admin/exercises/'
      preLoaderRoute: typeof AppAdminExercisesIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/workouts/edit/$id/': {
      id: '/app/workouts/edit/$id/'
      path: '/workouts/edit/$id'
      fullPath: '/app/workouts/edit/$id/'
      preLoaderRoute: typeof AppWorkoutsEditIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/workout-templates/not-found/': {
      id: '/app/admin/workout-templates/not-found/'
      path: '/workout-templates/not-found'
      fullPath: '/app/admin/workout-templates/not-found/'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesNotFoundIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/workout-templates/create/': {
      id: '/app/admin/workout-templates/create/'
      path: '/workout-templates/create'
      fullPath: '/app/admin/workout-templates/create/'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesCreateIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
    '/app/admin/workout-templates/edit/$id/': {
      id: '/app/admin/workout-templates/edit/$id/'
      path: '/workout-templates/edit/$id'
      fullPath: '/app/admin/workout-templates/edit/$id/'
      preLoaderRoute: typeof AppAdminWorkoutTemplatesEditIdIndexRouteImport
      parentRoute: typeof AppAdminRouteRoute
    }
  }
}

interface AppAdminRouteRouteChildren {
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminExercisesIndexRoute: typeof AppAdminExercisesIndexRoute
  AppAdminWorkoutTemplatesIndexRoute: typeof AppAdminWorkoutTemplatesIndexRoute
  AppAdminWorkoutTemplatesCreateIndexRoute: typeof AppAdminWorkoutTemplatesCreateIndexRoute
  AppAdminWorkoutTemplatesNotFoundIndexRoute: typeof AppAdminWorkoutTemplatesNotFoundIndexRoute
  AppAdminWorkoutTemplatesEditIdIndexRoute: typeof AppAdminWorkoutTemplatesEditIdIndexRoute
}

const AppAdminRouteRouteChildren: AppAdminRouteRouteChildren = {
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminExercisesIndexRoute: AppAdminExercisesIndexRoute,
  AppAdminWorkoutTemplatesIndexRoute: AppAdminWorkoutTemplatesIndexRoute,
  AppAdminWorkoutTemplatesCreateIndexRoute:
    AppAdminWorkoutTemplatesCreateIndexRoute,
  AppAdminWorkoutTemplatesNotFoundIndexRoute:
    AppAdminWorkoutTemplatesNotFoundIndexRoute,
  AppAdminWorkoutTemplatesEditIdIndexRoute:
    AppAdminWorkoutTemplatesEditIdIndexRoute,
}

const AppAdminRouteRouteWithChildren = AppAdminRouteRoute._addFileChildren(
  AppAdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAdminRouteRoute: typeof AppAdminRouteRouteWithChildren
  AppLogWorkoutIndexRoute: typeof AppLogWorkoutIndexRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
  AppWorkoutsInvalidIndexRoute: typeof AppWorkoutsInvalidIndexRoute
  AppWorkoutsNotFoundIndexRoute: typeof AppWorkoutsNotFoundIndexRoute
  AppWorkoutsEditIdIndexRoute: typeof AppWorkoutsEditIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRouteRoute: AppAdminRouteRouteWithChildren,
  AppLogWorkoutIndexRoute: AppLogWorkoutIndexRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
  AppWorkoutsInvalidIndexRoute: AppWorkoutsInvalidIndexRoute,
  AppWorkoutsNotFoundIndexRoute: AppWorkoutsNotFoundIndexRoute,
  AppWorkoutsEditIdIndexRoute: AppWorkoutsEditIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
